parameters:

    #
    # Services
    #
    elcodi_templates.wizard_status.service.class: Elcodi\Plugin\StoreSetupWizardBundle\Services\WizardStatus
    elcodi_templates.wizard_routes.service.class: Elcodi\Plugin\StoreSetupWizardBundle\Services\WizardRoutes

    #
    # Event Listeners
    #
    elcodi_plugin.event_listener.dashboard_redirection.class: Elcodi\Plugin\StoreSetupWizardBundle\EventListener\DashboardRedirectionEventListener
    elcodi_plugin.event_listener.disable_wizard.class: Elcodi\Plugin\StoreSetupWizardBundle\EventListener\DisableWizardEventListener
    elcodi_plugin.event_listener.disable_under_construction.class: Elcodi\Plugin\StoreSetupWizardBundle\EventListener\DisableUnderConstructionEventListener
