services:

    #
    # Event listeners
    #
    elcodi_plugin.event_listener.dashboard_redirection:
        class: Elcodi\Plugin\StoreSetupWizardBundle\EventListener\DashboardRedirectionEventListener
        arguments:
            - @router
            - @elcodi_templates.wizard_status.service
            - @elcodi_templates.wizard_routes.service
        calls:
            - [setPlugin, [@=elcodi_plugin("Elcodi\\Plugin\\StoreSetupWizardBundle")]]
        tags:
            - { name: firewall_listener, firewall: admin_area }

    elcodi_plugin.event_listener.disable_wizard:
        class: Elcodi\Plugin\StoreSetupWizardBundle\EventListener\DisableWizardEventListener
        arguments:
            - @elcodi_templates.wizard_status.service
            - @elcodi.manager.plugin
            - @elcodi.manager.configuration
        calls:
            - [setPlugin, [@=elcodi_plugin("Elcodi\\Plugin\\StoreSetupWizardBundle")]]
        tags:
            - { name: firewall_listener, firewall: admin_area }

    elcodi_plugin.event_listener.disable_under_construction:
        class: Elcodi\Plugin\StoreSetupWizardBundle\EventListener\DisableUnderConstructionEventListener
        arguments:
            - @translator
            - @router
            - @elcodi_templates.wizard_status.service
            - @elcodi.manager.configuration
        calls:
            - [setPlugin, [@=elcodi_plugin("Elcodi\\Plugin\\StoreSetupWizardBundle")]]
        tags:
            - { name: firewall_listener, firewall: admin_area }
