services:

    #
    # Event listeners
    #
    elcodi_plugin.event_listener.dashboard_redirection:
        class: %elcodi_plugin.event_listener.dashboard_redirection.class%
        arguments:
            router: @router
            wizard_status: @elcodi_templates.wizard_status.service
            wizard_routes: @elcodi_templates.wizard_routes.service
        calls:
            - [setPlugin, [@=elcodi_plugin("Elcodi\\Plugin\\StoreSetupWizardBundle")]]
        tags:
            - { name: firewall_listener, firewall: admin_area }

    elcodi_plugin.event_listener.disable_wizard:
        class: %elcodi_plugin.event_listener.disable_wizard.class%
        arguments:
            wizard_status: @elcodi_templates.wizard_status.service
            plugin_manager: @elcodi.plugin_manager
            configuration_manger: @elcodi.manager.configuration
        calls:
            - [setPlugin, [@=elcodi_plugin("Elcodi\\Plugin\\StoreSetupWizardBundle")]]
        tags:
            - { name: firewall_listener, firewall: admin_area }

    elcodi_plugin.event_listener.disable_under_construction:
        class: %elcodi_plugin.event_listener.disable_under_construction.class%
        arguments:
            translator: @translator
            router: @router
            wizard_status: @elcodi_templates.wizard_status.service
            configuration_manager: @elcodi.manager.configuration
        calls:
            - [setPlugin, [@=elcodi_plugin("Elcodi\\Plugin\\StoreSetupWizardBundle")]]
        tags:
            - { name: firewall_listener, firewall: admin_area }
