services:

    #
    # Services
    #
    elcodi_plugin.store_setup_wizard.wizard_status:
        class: Elcodi\Plugin\StoreSetupWizardBundle\Services\WizardStatus
        arguments:
            - @elcodi.manager.configuration
            - @elcodi.repository.product
            - @elcodi.repository.shipping_range
            - @elcodi.enabled_payment_plugins

    elcodi_plugin.store_setup_wizard.wizard_routes:
        class: Elcodi\Plugin\StoreSetupWizardBundle\Services\WizardRoutes
        arguments:
            - @elcodi_plugin.store_setup_wizard.wizard_status
