services:

    #
    # Services
    #
    elcodi_templates.wizard_status.service:
        class: Elcodi\Plugin\StoreSetupWizardBundle\Services\WizardStatus
        arguments:
            - @elcodi.manager.configuration
            - @elcodi.repository.product
            - @elcodi.repository.shipping_range
            - %store.payment_bridge.enabled_methods%

    elcodi_templates.wizard_routes.service:
        class: Elcodi\Plugin\StoreSetupWizardBundle\Services\WizardRoutes
        arguments:
            - @elcodi_templates.wizard_status.service
