services:

    #
    # Twig renderer
    #
    elcodi_plugin.store_setup_wizard.renderer:
        class: Elcodi\Plugin\StoreSetupWizardBundle\Templating\TwigRenderer
        calls:
            - [setTemplating, [@twig]]
            - [setPlugin, [@=elcodi_plugin("Elcodi\\Plugin\\StoreSetupWizardBundle")]]
        arguments:
            - @elcodi_templates.wizard_status.service
            - @request_stack
            - @elcodi.manager.configuration
            - @elcodi_templates.wizard_routes.service
            - @elcodi.repository.carrier
        tags:
            - { name: kernel.event_listener, event: admin.body_top, method: renderMiniWizard }
            - { name: kernel.event_listener, event: admin.body_top, method: renderEnableStoreMessage }
            - { name: kernel.event_listener, event: admin.body_top, method: renderGoNextStepMessage }
            - { name: kernel.event_listener, event: admin.body_top, method: renderDisableUnderConstructionMode }
