author: Roger Gros
description: |
    A wizard to setup the store for the first time.
    On the first step it configures the physical address and the store owner
    data. After all it aims to add the first category, product and manufacturer
    and at the end asks the store administrator for the carrier and payment data
year: 2015
name: Setup Wizard
url: http://elcodi.io/
fa_icon: magic
configuration_route: admin_store_setup_wizard_configuration
version: ~0.4
enabled: true
visible: false
